import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import type { DocumentView, VersionRef } from '../../shared/contracts.js';
import { api, versionRoute } from '../../shared/client/api-client.js';
import { OperationTracker, type OperationState } from '../../shared/client/operation-tracker.js';
import { useDirty } from '../../app/WorkspaceShell.js';
import { beginEdit, editDraft, isDirty } from './editor-state.js';
import { ErrorNotice } from './ErrorNotice.js';
import { ConfirmDialog } from './ConfirmDialog.js';
export function DocumentEditor({ view, saved, cancel, onConflict }: { view: DocumentView; onConflict: (ref: VersionRef) => void; saved: (view: DocumentView, changed: boolean) => void; cancel: () => void }) {
  const [editor, setEditor] = useState(() => beginEdit(view)); const [state, setState] = useState<OperationState>({ status: 'idle' }); const tracker = useRef(new OperationTracker(api, setState)); const [confirm, setConfirm] = useState<'cancel' | 'retry' | null>(null);
  useDirty(isDirty(editor) && state.status !== 'succeeded');
  useEffect(() => { if (state.status === 'succeeded' && state.data && 'view' in state.data) saved(state.data.view, state.data.changed); if (state.status === 'conflict' && state.error?.currentVersionRef) onConflict(state.error.currentVersionRef); }, [state]);
  return <section className="editor"><div className="notice">v{view.versionNumber} 기준 편집 · 저장하면 새 버전으로 보관됩니다. 과거 내용은 유지됩니다.</div><label>문서 본문<textarea className="document-textarea" autoFocus data-testid="document-editor-input" value={editor.draft} disabled={state.status === 'saving'} spellCheck={false} onChange={e => setEditor(s => editDraft(s, e.target.value))} /></label><div className="editor-meta"><span>{new TextEncoder().encode(editor.draft).length.toLocaleString()} / 1,048,576 bytes</span><span>{isDirty(editor) ? '저장하지 않은 변경' : '변경 없음'}</span></div><ErrorNotice error={state.error} />{state.error?.currentVersionRef && <p><Link data-testid="editor-latest-link" to={versionRoute(state.error.currentVersionRef)}>최신 버전 열기 · 초안을 복사한 뒤 비교하세요</Link></p>}<p role="status">{state.message}</p>{state.status === 'unknown' && <div className="actions"><button data-testid="editor-check-button" onClick={() => void tracker.current.check()}>저장 결과 다시 확인</button><button data-testid="editor-new-attempt-button" onClick={() => setConfirm('retry')}>새 시도 준비</button></div>}<div className="actions"><button data-testid="editor-cancel-button" disabled={state.status === 'saving'} onClick={() => isDirty(editor) ? setConfirm('cancel') : cancel()}>편집 취소</button><button className="primary" data-testid="editor-save-button" disabled={['saving', 'unknown'].includes(state.status)} onClick={() => void tracker.current.submit(`/api/srs/${view.srId}/documents/${view.documentId}/edits`, { versionId: editor.base.versionId, body: editor.draft })}>{state.status === 'saving' ? '저장 중…' : '새 버전 저장'}</button></div>{confirm && <ConfirmDialog title={confirm === 'cancel' ? '편집을 취소할까요?' : '새 저장 시도 준비'} label={confirm === 'cancel' ? '변경 버리기' : '새 시도 준비'} cancel={() => setConfirm(null)} confirm={() => { if (confirm === 'cancel') cancel(); else tracker.current.reset(); setConfirm(null); }}><p>{confirm === 'cancel' ? '저장되지 않은 본문 변경이 사라집니다.' : '이전 요청이 나중에 완료될 수 있습니다. 결과를 확인하지 않고 새로 저장하면 중복될 수 있습니다.'}</p></ConfirmDialog>}</section>;
}
